name: Update eksctl

on:
  push:
  schedule:
    # Run the workflow every day at 00:00 UTC
    - cron: "0 0 * * *"

permissions:
  pull-requests: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update_eksctl:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup micromamba
      uses: mamba-org/provision-with-micromamba@v15
      with:
        environment-file: false
        cache-downloads: true
        cache-env: true
        channels: conda-forge
        extra-specs: conda-build

    - name: Download latest eksctl release
      run: |
        EKSCTL_URL=$(curl --silent https://api.github.com/repos/weaveworks/eksctl/releases/latest | jq -r '.assets[] | select(.name | ascii_downcase | contains("linux_amd64.tar.gz")).browser_download_url')
        mkdir -p linux-64
        curl -L --progress-bar --location "$EKSCTL_URL" | tar -xz --wildcards --no-anchored 'eksctl' -O > linux-64/eksctl

    - name: Build eksctl Conda package
      run: |
        mkdir -p recipe

        cat > recipe/meta.yaml <<EOL
        package:
          name: eksctl
          version: $(curl --silent https://api.github.com/repos/weaveworks/eksctl/releases/latest | jq -r '.tag_name' | sed 's/^v//')
        EOL

        cat >> recipe/meta.yaml <<'EOL'
        source:
          path: ../linux-64

        build:
          number: 0
          binary_relocation: false
          script: |
            mkdir -p $PREFIX/bin
            cp -r $SRC_DIR/* $PREFIX/bin
            chmod +x $PREFIX/bin/eksctl

        test:
          commands:
            - eksctl version

        about:
          home: https://github.com/weaveworks/eksctl
          license: Apache-2.0
          summary: A CLI for Amazon EKS
          description: eksctl is a simple CLI tool for creating and managing clusters on EKS - Amazon's managed Kubernetes service for EC2.
        EOL

        micromamba install -y -c conda-forge conda-build
        conda config --add pkgs_dirs ~/conda_pkgs_dir
        conda build recipe

    - name: Create Conda Channel Directory Structure
      run: |
        mkdir -p conda-channel/linux-64
        cp /usr/share/miniconda/conda-bld/linux-64/eksctl*.tar.bz2 conda-channel/linux-64/
        conda index conda-channel/linux-64

    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload Conda Channel as GitHub Pages Artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: conda-channel/
    - name: Deploy Conda Channel to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
